F07 : Algo finish - useContex
Tshoms/mrtshomsburger pull request #7
Opened 2023-01-12 21:06 UTC by Tshoms

2023-06-16 16:30 UTC, vileaddev requested changes
Très bien, preeeesque fini. Je te laisse corriger l'histoire du className en 30 sec et après je validerai quand tu m'enverras la dernière version de la PR

2023-06-16 16:30 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
>    const userName = searchParams.get("userName");
```suggestion
  const { username } = useParams();
```

2023-06-16 16:30 UTC, vileaddev commented on src/components/pages/order/Main/Admin/AdminTabs.js
> +      <Tab
code smell, code duplication

2023-06-16 16:30 UTC, vileaddev commented on src/components/pages/order/Main/Admin/Admin.js
> +  const { isCollapsed } = useContext(OrderContext);
yes !

2023-06-16 16:30 UTC, vileaddev commented on src/components/pages/order/Main/Admin/AdminPanels.js
> +      {isAddSelected ? <TabAdd /> : ""}
```suggestion
      {isAddSelected && <TabAdd />}
```

pareil pour la ligne du dessous

2023-06-16 16:30 UTC, vileaddev commented on src/components/pages/order/Main/Admin/AdminTabs.js
> +    isAddSelected,
<img width="257" alt="image" src="https://github.com/Tshoms/mrtshomsburger/assets/110701253/d36d968b-854d-46c7-aa9b-243cd1809242">

Si tu regardes le live AMA, tu peux remplacer les 4 lignes par une seule et on code sera bien plus scalable 💡

2023-06-16 16:30 UTC, vileaddev commented on src/components/pages/order/Main/Admin/TabsConfig.js
> +    icon: <MdModeEditOutline className="icon" />,
```suggestion
    icon: <MdModeEditOutline />,
```

"className" ne doit pas être ici dans un fichier de config et non de JSX. Faut déplacer className dans le fichier de composant / JSX. Ici, limite un non techos est censé modifier ce fichier sans répercussion sur le code.

2023-06-16 16:30 UTC, vileaddev commented on src/components/pages/order/Main/Admin/select/SelectPub.js
> +export default function SelectPub() {
pas de commentaire sur ce composant pour l'instant.

2023-06-16 16:30 UTC, vileaddev commented on src/components/pages/order/Main/Admin/tabs/TabUpdate.js
> +export default function TabUpdate() {
```suggestion
export default function UpdateForm() {
```

2023-06-16 16:30 UTC, vileaddev commented on src/components/pages/order/Main/Admin/tabs/TabAdd.js
> +export default function TabsAdd() {
```suggestion
export default function AddForm() {
```

2023-06-16 20:37 UTC, Tshoms commented on src/components/pages/order/OrderPage.js
>    const userName = searchParams.get("userName");
J'ai supprimer la méthode "useSearchParams" de la page OrderPage.js et importé dans le composent Profile.js . J'ai utilisé la méthode "useSearchParams" dans Profile.js plutôt que la méthode "useParams" (choix personnel) .

2023-06-17 00:02 UTC, vileaddev approved these changes
OK pour moi :) je valide, tu peux merge la PR :))

2023-06-19 08:37 UTC, merged